version: '2.2'

services:
  money5:
    image: 'cloud:latest'

    build: ./
    ports:
      - '8080:8080'
    volumes:
      - C:\front\
    command: npm run build

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "habrpguser"
      POSTGRES_PASSWORD: "pgpwd4habr"
    ports:
      - "5432:5432"